
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Admin_changePassword extends javax.swing.JFrame {

    
    String username;
    public Admin_changePassword(String username) {
        initComponents();
        this.username = username;
        setSize(500, 600);
        setVisible(true);
        setLocation(700,250);
        getContentPane().setBackground(new Color(153,255,204));
        j_user.setText(username);
        j_user.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        j_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        j_old_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j_confirm_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        j_new_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 140, 130, 40);
        getContentPane().add(j_user);
        j_user.setBounds(150, 140, 260, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Old Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 210, 140, 40);
        getContentPane().add(j_old_pass);
        j_old_pass.setBounds(150, 210, 260, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 280, 120, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Confirm New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 370, 150, 40);
        getContentPane().add(j_confirm_pass);
        j_confirm_pass.setBounds(160, 370, 250, 40);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 440, 150, 50);

        jButton2.setText("<-Back to Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 20, 130, 30);
        getContentPane().add(j_new_pass);
        j_new_pass.setBounds(150, 280, 260, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Change Password ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 70, 280, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String oldpass = j_old_pass.getText().toString();
        String newpass = j_new_pass.getText().toString();
        String confirmpass = j_confirm_pass.getText().toString();
        
        if(oldpass.equals("") || newpass.equals("") || confirmpass.equals("")){
            JOptionPane.showMessageDialog(rootPane, " All fields are required");
        }
        else if(newpass.equals(confirmpass)){
            try {
                
                HttpResponse<String> httpResponse = Unirest.get(GlobalClass.ip+"admin_change_pass")
                        .queryString("username",username)
                        .queryString("oldpass",oldpass)
                        .queryString("newpass",newpass)
                        .asString();
                
                if(httpResponse.getStatus() == 200 ){
                    String res = httpResponse.getBody();
                    JOptionPane.showMessageDialog(rootPane, res);
                }
                
                
                
                
            } catch (UnirestException ex) {
                Logger.getLogger(Admin_changePassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        else {
            JOptionPane.showMessageDialog(rootPane, " New password and confirm password must match.");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Admin_Home obj=new Admin_Home(username);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Admin_changePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField j_confirm_pass;
    private javax.swing.JPasswordField j_new_pass;
    private javax.swing.JPasswordField j_old_pass;
    private javax.swing.JTextField j_user;
    // End of variables declaration//GEN-END:variables
}
