/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class category_panel extends javax.swing.JPanel {

    /**
     * Creates new form category_panel
     */
    public category_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_text = new javax.swing.JLabel();
        jScrollPanecategory = new javax.swing.JScrollPane();
        j_cat_panel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 255));
        setLayout(null);

        j_text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(j_text);
        j_text.setBounds(30, 30, 350, 50);

        j_cat_panel.setBackground(new java.awt.Color(255, 255, 102));
        j_cat_panel.setPreferredSize(new java.awt.Dimension(1000, 1000));
        j_cat_panel.setLayout(null);
        jScrollPanecategory.setViewportView(j_cat_panel);

        add(jScrollPanecategory);
        jScrollPanecategory.setBounds(20, 100, 660, 190);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPanecategory;
    public javax.swing.JPanel j_cat_panel;
    public javax.swing.JLabel j_text;
    // End of variables declaration//GEN-END:variables
}
