/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Rooms_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Rooms_Panel
     */
    public Rooms_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jroom_img = new javax.swing.JLabel();
        jroom_text = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 204));
        setLayout(null);

        jroom_img.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jroom_img.setText("jLabel1");
        jroom_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jroom_img);
        jroom_img.setBounds(10, 20, 170, 130);

        jroom_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jroom_text.setText("jLabel2");
        add(jroom_text);
        jroom_text.setBounds(10, 150, 190, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jroom_img;
    public javax.swing.JLabel jroom_text;
    // End of variables declaration//GEN-END:variables
}
