
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class User_Signup extends javax.swing.JFrame {

    /**
     * Creates new form User_Signup
     */
    JFileChooser jfc=new JFileChooser();
    File obj_file;
    public User_Signup() {
        initComponents();
        setSize(550,600);
        setVisible(true);
        getContentPane().setBackground(new Color(153,255,204));
        j_sec_que.removeAllItems();
        for(int i=0;i<GlobalClass.sec_que.length;i++)
        {
            j_sec_que.addItem(GlobalClass.sec_que[i]);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j_img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        juser = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jconpass = new javax.swing.JPasswordField();
        j_sec_que = new javax.swing.JComboBox<>();
        j_secans = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Security Question");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 270, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Security Answer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 320, 110, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Photo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 390, 100, 40);

        j_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(j_img);
        j_img.setBounds(150, 360, 160, 130);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 380, 100, 40);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 500, 90, 50);
        getContentPane().add(juser);
        juser.setBounds(150, 30, 340, 30);
        getContentPane().add(jemail);
        jemail.setBounds(150, 70, 340, 30);
        getContentPane().add(jpass);
        jpass.setBounds(150, 110, 340, 30);
        getContentPane().add(jconpass);
        jconpass.setBounds(150, 160, 340, 30);

        j_sec_que.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(j_sec_que);
        j_sec_que.setBounds(150, 270, 340, 30);
        getContentPane().add(j_secans);
        j_secans.setBounds(150, 320, 340, 30);
        getContentPane().add(jphone);
        jphone.setBounds(150, 210, 340, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Mobile Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 220, 100, 20);

        jButton3.setText("<-Back to Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 10, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ans=jfc.showOpenDialog(this);
        if(ans==JFileChooser.APPROVE_OPTION)
        {
            obj_file=jfc.getSelectedFile();
            System.out.println(""+obj_file.getAbsolutePath());
            j_img.setText(obj_file.getPath());
             //set Image into label
            ImageIcon icon=new ImageIcon(obj_file.getPath());
            Image img=icon.getImage();
            Image newImage=img.getScaledInstance(j_img.getWidth(),j_img.getHeight(),Image.SCALE_SMOOTH);
            j_img.setIcon(new ImageIcon(newImage));
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String username=juser.getText().toString();
        String email=jemail.getText().toString();
        String password=jpass.getText().toString();
        String confirmpassword=jconpass.getText().toString();
        String mobileno=jphone.getText().toString();
        String sec_ques=j_sec_que.getSelectedItem().toString();
        String sec_ans=j_secans.getText().toString();
        if(username.isEmpty()|| email.isEmpty()|| password.isEmpty()||confirmpassword.isEmpty()||mobileno.isEmpty()||sec_ans.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane,"All Fields are mandatory");
        }
        else if(password.equals(confirmpassword))
        {
            try {
                HttpResponse<String> httpresponse=Unirest.post(GlobalClass.ip+"user_signup")
                        .queryString("username",username)
                        .queryString("password",password)
                        .queryString("email",email)
                        .queryString("mobile_no",mobileno)
                        .queryString("sec_ques",sec_ques)
                        .queryString("sec_ans",sec_ans)
                        .field("photo", obj_file)
                        .asString();
                if(httpresponse.getStatus()==200)
                {
                    String res=httpresponse.getBody();
                    JOptionPane.showMessageDialog(rootPane, res);
                }
            } catch (UnirestException ex) {
                Logger.getLogger(User_Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Password and Confirm Password does not match");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        User_Login obj=new User_Login();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel j_img;
    private javax.swing.JComboBox<String> j_sec_que;
    private javax.swing.JTextField j_secans;
    private javax.swing.JPasswordField jconpass;
    private javax.swing.JTextField jemail;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
